services:
  - type: web
    name: novawear-backend
    env: node
    rootDir: Back-end
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
